package(default_visibility = ["//ipu_tensorflow_addons:__subpackages__"])

py_library(
    name = "test_utils",
    srcs = [
        "__init__.py",
        "hardware_test_utils.py",
        "report_helper.py",
        "test_case_extensions.py",
    ],
)
