package(default_visibility = [
    "//docs:__pkg__",
    "//ipu_tensorflow_addons/tools/pip_package:__pkg__",
])

py_library(
    name = "ipu_tensorflow_addons",
    srcs = ["__init__.py"],
    deps = [
        "//ipu_tensorflow_addons/keras/layers",
        "//ipu_tensorflow_addons/keras/optimizers",
        "//ipu_tensorflow_addons/util",
        "//ipu_tensorflow_addons/v1/layers",
        "//ipu_tensorflow_addons/v1/optimizers",
    ],
)
