# Copyright (c) 2021 Graphcore Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

import os
import re
from setuptools import setup

# `_dependency_versions` is generated by
# `//ipu_tensorflow_addons/util:_dependency_versions`.
from _dependency_versions import TENSORFLOW_VERSION


def find_packages(pattern=r".*"):
  packages = []
  for root, _, files in os.walk(".", followlinks=True):
    for name in files:
      if name == "__init__.py":
        dir_path = os.path.relpath(root)
        package_name = ".".join(dir_path.split(os.sep))
        if re.fullmatch(pattern, package_name) is not None:
          packages.append(package_name)
  return packages


setup(
    name='ipu_tensorflow_addons',
    description='A collection of addons for IPU TensorFlow',
    version=TENSORFLOW_VERSION,
    python_requires='>=3.6',
    url='https://www.graphcore.ai/',
    author='Graphcore Ltd.',
    # Contained modules and scripts.
    packages=find_packages(r"ipu_tensorflow_addons\.?.*"),
    license='Apache 2.0',
)
